# -*- coding: utf-8 -*-
"""kalkulator rara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NkvQyRgO7UgJ2qGXLfzQfGQQzqWcJsz
"""

import streamlit as st

# Fungsi untuk menghitung suku ke-n
def hitung_suku_ke_n(a, d, n):
    return a + (n - 1) * d

# Fungsi untuk menghitung jumlah n suku pertama
def hitung_jumlah_n_suku(a, d, n):
    return (n / 2) * (2 * a + (n - 1) * d)

# Fungsi untuk menampilkan barisan aritmatika
def tampilkan_barisan(a, d, n):
    return [a + (i * d) for i in range(n)]

# Streamlit UI
st.title("📐 Kalkulator Barisan Aritmatika")
st.markdown("Masukkan nilai-nilai berikut untuk menghitung barisan aritmatika:")

# Input user
a = st.number_input("Suku pertama (a)", value=1.0)
d = st.number_input("Beda (d)", value=1.0)
n = st.number_input("Jumlah suku (n)", min_value=1, step=1)

# Tombol untuk menghitung
if st.button("Hitung"):
    suku_ke_n = hitung_suku_ke_n(a, d, n)
    jumlah_n_suku = hitung_jumlah_n_suku(a, d, n)
    barisan = tampilkan_barisan(a, d, int(n))

    st.success(f"Suku ke-{int(n)} adalah: {suku_ke_n}")
    st.success(f"Jumlah {int(n)} suku pertama adalah: {jumlah_n_suku}")
    st.write("Barisan Aritmatika:")
    st.write(barisan)

# Footer
st.markdown("---")
st.caption("Dibuat dengan ❤️ oleh Rara Anisa Nabilah")

"""Alamat saya didesa tegal suruh dan saya berangkat kuliah menggunakan motor"""

